name: Feature request
description: Suggest a feature or improvement for the snowballr-ci repo
title: "[Feature]: <title>"
labels: ["enhancement"]
projects: ["SE-UUlm/2"]

body:
    - type: textarea
      id: description
      attributes:
          label: Is your request related to a problem? Please describe.
          description: A clear description of what problem you're trying to solve.
          placeholder: I'm frustrated when I can't [...]
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Describe the solution you'd like
          description: What should the ci repos do or support?
          placeholder: I want the ci repo to provide a workflow that [...]
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Describe alternatives you've considered
          description: Any other solutions or workarounds you've thought about.
      validations:
          required: false

    - type: textarea
      id: additional-context
      attributes:
          label: Anything else?
          description: |
              Any extra context, drawings, or examples that help us understand your request.

              Tip: You can drag and drop files here.
      validations:
          required: false
