name: Git Conventions

on:
    pull_request:
        branches:
            - main

jobs:
    ensure-linear-history:
        name: Ensure Linear Git History
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Run Check
              uses: ./src/ensure-linear-history
              with:
                  target-branch: main

    ensure-conventional-commits:
        name: Ensure Conventional Commits
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
                  ref: ${{ github.head_ref }}

            - name: Run Check
              uses: ./src/ensure-conventional-commits
              with:
                  target-branch: main

    ensure-conventional-branches:
        name: Ensure Conventional Branches
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Run Check
              uses: ./src/ensure-conventional-branches
              with:
                  branch-name: ${{ github.head_ref }}
